on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  alpha:
    name: Job Alpha
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "Within Job Alpha."

  beta:
    name: Job Beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "Within Job Beta." && exit 1

  gamma:
    name: Job Gamma
    runs-on: ubuntu-latest
    needs: [alpha, beta]
    if: ${{ always() && contains(join(needs.*.result, ','), 'success') }}
    steps:
      - uses: actions/checkout@v3

      - name: Set current date as env variable
        run: echo "Within Job Gamma."
